### ISSUE TITLE
comment function

### ISSUE THREAD

**Issue by MelissaDuve** [MelissaDuve/capstone-project#13]
## Value Proposition

As a cocktail enthusiast
I would like to comment the cocktail I mixed and tasted
so other people can see my comment 
​

## Description

![Unbenannt-2023-03-16-1142](https://user-images.githubusercontent.com/121951147/225597949-11c9b780-06de-4d36-b35a-8ec26dce2f65.png)

​

## Acceptance Criteria

- a submit Button is displayed
- a form for name, date and text input is displayed
- filling in the entries is required
- store in localStorage
      ​

## Tasks

- create form with inputs
- create submit button
- ​localStorage

**Comment by Tim-K93** [comment]
lgtm! :)
