### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by MelissaDuve** [MelissaDuve/capstone-project#15]
## Value Proposition

As a user
I want to be able to delete a comment  
when I have changed my mind
​

##Description
![Delete Button](https://user-images.githubusercontent.com/121951147/226840241-06389436-ad13-4d4d-bcae-d8dc693e3fd6.png)

​
## Acceptance Criteria

- a delete button is displayed next to the comment
- delete button removes only one comment
      ​

## Tasks

- uid for each comment​
- function with onClick

**Comment by pung-one** [comment]
a good user story!
