### ISSUE TITLE
fetch & display Api

### ISSUE THREAD

**Issue by MelissaDuve** [MelissaDuve/capstone-project#3]
## Value Proposition

As a cocktail enthusiast
I want to see a list of all cocktails
so that i can get an overview. 
​

## Description
![MyApp-2023-02-27-1054(1)](https://user-images.githubusercontent.com/121951147/222704377-377bb5cc-a0c2-47df-b6f8-f348ece7e60d.png)

​

## Acceptance Criteria

- all cocktails are displayed 
- the image of each cocktail is displayed
- the title of each cocktails is displayed
      ​

## Tasks

- create a branch
- fetch all cocktails with SWR in _app.js
- create the component CocktailsOverview to render a list
- don't forget the props

**Comment by pung-one** [comment]
this is a user story that is very good!
