### ISSUE TITLE
Cocktail detail page

### ISSUE THREAD

**Issue by MelissaDuve** [MelissaDuve/capstone-project#4]
## Value Proposition

As a a cocktail enthusiast
I want to be able to see the detail information of each cocktail
so that i can see the recipe with the ingredients and start to mix. 

​
## Description
![MyApp-2023-02-27-1054(1)](https://user-images.githubusercontent.com/121951147/222730137-a6f86551-6ef0-435f-ae73-4b87659e223b.png)

​

## Acceptance Criteria

- clicking a cocktail from the list shows the detail page
- the cocktail category, name, image, instructions and ingredients are displayed
- a back-button is displayed
      ​

## Tasks

- create a branch
- Details Page ("/cocktails/id")
- create the component CocktailDetails
- don't forget the props
      ​

**Comment by SarahWett** [comment]
Nice one! 🚀 "don't forget the props" is pretty cute!
