### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by MelissaDuve** [MelissaDuve/capstone-project#5]
## Value Proposition

As a cocktail enthusiast
I want to be able to switch between the pages
so that I can navigate the app easier.
​

## Description

![MyApp-2023-02-27-1054(3)](https://user-images.githubusercontent.com/121951147/222744724-ccf6fe83-8fa8-4460-8c1f-4f2e8cd56a3e.png)

​

## Acceptance Criteria

- a navigation link for "home" is displayed
- a navigation link for "favorites" is displayed
- a navigation link for "shopping list" is displayed
- a navigation link for "home" is displayed
      ​

## Tasks

- create a branch
- create the component Navigation that renders all navigation links
- hint: global state
- don't forget the props 
      ​

**Comment by SarahWett** [comment]
Nice!
