### ISSUE TITLE
Favorite Toggle Button

### ISSUE THREAD

**Issue by MelissaDuve** [MelissaDuve/capstone-project#6]
## Value Proposition

As a cocktail enthusiast
I want to mark my favorite cocktail recipes as favorites
so that I can find them easier. 
​

## Description

![MyApp-2023-02-27-1054(4)](https://user-images.githubusercontent.com/121951147/222896993-253ca588-2e3c-4162-93f6-321eaf467592.png)

​

## Acceptance Criteria

- the favorite-button is displayed in home (CocktailsOverview)
- the favorite-button is displayed in the details page
      ​

## Tasks

- create a branch
- create the page favorites.js
- create the component FavoriteButton
- render the FavoriteButton component in the CocktailsOverview & CocktailDetails component
- hint: global state
- don't forget the props
      ​

**Comment by Yasin-Goenendi** [comment]
looks nice :)
