### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by MelissaDuve** [MelissaDuve/capstone-project#8]
## Value Proposition

As a User
I want to see a nice welcome page layout
so that I feel i am welcome.
​

## Description

​
![MyApp-2023-02-27-1054(5)](https://user-images.githubusercontent.com/121951147/223665075-18f7bf7e-e5dd-4990-bffe-175fd358b7c5.png)

## Acceptance Criteria

- an image for the whole page is displayed
- a welcome text on the image is displayed
- a Button with a Link to all cocktails is displayed
      ​

## Tasks

- create a branch
- create the folder structure and work in index.js
- create a Button
- don't forget the props 
      ​

**Comment by Manu7864z** [comment]
don't forget the props :D looks good to me!

**Comment by kebab-case-dev** [comment]
looks great
